# Generated by Django 3.1.4 on 2020-12-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='MAC',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='MAC地址'),
        ),
    ]
